# Generated by Django 4.2.10 on 2024-02-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rooms_roomimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(upload_to='block_images/')),
                ('block_no', models.CharField(blank=True, max_length=300)),
                ('description', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
