# Generated by Django 4.2.10 on 2024-02-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocks',
            name='no_of_rooms',
            field=models.IntegerField(default=0),
        ),
    ]
