# Generated by Django 4.2.10 on 2024-02-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees_structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('description', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='rooms',
            name='image',
            field=models.FileField(default='image', upload_to='room_images/'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='image2',
            field=models.FileField(default='image1', upload_to='room_images/'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='image3',
            field=models.FileField(default='image2', upload_to='room_images/'),
        ),
        migrations.DeleteModel(
            name='RoomImages',
        ),
    ]
