# Generated by Django 4.2.10 on 2024-02-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_fees_structure_rooms_image_rooms_image2_rooms_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='no_of_adults',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='rooms',
            name='size',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
