# Generated by Django 4.1.2 on 2024-02-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_events_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mess_food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100, null=True)),
                ('breakfast', models.CharField(max_length=100, null=True)),
                ('lunch', models.CharField(max_length=100, null=True)),
                ('dinner', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
