# Generated by Django 4.1.2 on 2024-02-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_mess_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(null=True)),
                ('check_out', models.DateField(null=True)),
                ('adults', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='Free', max_length=100, null=True)),
                ('pay_status', models.CharField(default='null', max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Fees_structure',
        ),
    ]
