# Generated by Django 4.1.2 on 2024-02-12 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_room_booking_delete_fees_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_booking',
            name='rid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.rooms'),
        ),
        migrations.AddField(
            model_name='room_booking',
            name='uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.userreg'),
        ),
    ]
