# Generated by Django 4.2.10 on 2024-02-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_room_booking_rid_room_booking_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_booking',
            name='status',
            field=models.CharField(default='Booked', max_length=100, null=True),
        ),
    ]
