# Generated by Django 4.2.10 on 2024-02-14 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_hosteller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosteller',
            name='rid',
        ),
    ]
