# Generated by Django 4.2.10 on 2024-02-14 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_hosteller_rid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosteller',
            name='name',
        ),
    ]
