# Generated by Django 4.2.10 on 2024-02-21 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_mess_food_breakfast_mess_food_mess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mess_food',
            old_name='mess',
            new_name='breakfast',
        ),
    ]
