# Generated by Django 4.2.10 on 2024-02-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_rename_mess_mess_food_breakfast'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='type',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
