# Generated by Django 4.2.10 on 2024-02-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_rooms_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_booking',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
