# Generated by Django 4.2.10 on 2024-02-21 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_room_booking_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_booking',
            name='gid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.hosteller_reg'),
        ),
    ]
