# Generated by Django 4.2.10 on 2024-02-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
