# Generated by Django 4.2.10 on 2024-02-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_leave_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(blank=True, default='Requested', max_length=100, null=True),
        ),
    ]
